services:
  goapp:
    build: .
    volumes:
      - .:/go/app
    platform: linux/amd64
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_ROOT_PASSWORD: admin@123
      POSTGRES_DATABASE: api-avulso
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin@123
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-server:7.3.0
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.99.100:9092
      LISTENERS: PLAINTEXT://0.0.0.0:9092
    restart: always
