###
POST http://localhost:3000/api/user
Content-Type: application/json

{
    "name": "Kayane Soares de souza", 
    "birthday": "2004-03-19",
    "active": true
}


###
GET http://localhost:3000/api/user
Content-Type: application/json

###
DELETE http://localhost:3000/api/user/fca5f31c-b632-44f5-8fc7-854ac5913abf
